### ISSUE TITLE
Currently getting this error while calling get_user_content

### ISSUE THREAD

**Issue by montemurroPaolo** [ivan-rivera/RedditExtractor#33]
<html>
<body>

Error in page[[content_type]] : subscript out of bounds
--
 
  |  
 

<br class="Apple-interchange-newline">
</body>
</html>

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ivan-rivera** [comment]
@montemurroPaolo, thank you for reporting the bug. You'll need to be more specific though, the function works for me without issues and unless I can reproduce the problem, I cannot fix it. This could be caused by your environment (or how you are calling it) rather than the Reddit extractor package itself.

**Comment by ivan-rivera** [comment]
Please open a new issue with more information if this problem remains unresolved.
